# Generated by Django 2.0.2 on 2018-03-30 15:47


# ./manage.py makemigrations
# Migrations for 'question_answer':
#   question_answer/migrations/0001_initial.py
#     - Create model Answer
#     - Create model AnswerLike
#     - Create model Question
#     - Create model QuestionLike
#     - Create model QuestionTag
#     - Create model Tag
#     - Create model User
#     - Add field tad_id to questiontag
#     - Add field user_id to questionlike
#     - Add field user_id to question
#     - Add field user_id to answerlike
#     - Add field question_id to answer
#     - Add field user_id to answer

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('time', models.DateTimeField()),
                ('best_ansver', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AnswerLike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_answer.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionLike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_answer.Question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_answer.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.TextField()),
                ('nick_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.BinaryField()),
                ('avatar_link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='questiontag',
            name='tad_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_answer.Tag'),
        ),
        migrations.AddField(
            model_name='questionlike',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_answer.User'),
        ),
        migrations.AddField(
            model_name='question',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='question_answer.User'),
        ),
        migrations.AddField(
            model_name='answerlike',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_answer.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_answer.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='question_answer.User'),
        ),
    ]
