# Generated by Django 2.0.2 on 2018-04-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_answer', '0005_auto_20180401_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answerlike',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='status',
            field=models.IntegerField(),
        ),
    ]
