# Generated by Django 2.0.2 on 2018-04-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_answer', '0006_auto_20180401_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlike',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
