# Generated by Django 2.0.2 on 2018-04-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_answer', '0007_auto_20180401_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='best_ansver',
            new_name='best_answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
