# Generated by Django 2.0.2 on 2018-04-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_answer', '0008_auto_20180401_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontag',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='questiontag',
            name='tad_id',
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='question_answer.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='QuestionTag',
        ),
    ]
