# Generated by Django 2.0.2 on 2018-05-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_answer', '0009_auto_20180401_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_link',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
