# Generated by Django 2.0.2 on 2018-06-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_answer', '0010_auto_20180520_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcerptTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExcerptUsername',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars'),
        ),
    ]
